/* ============================================================
   games/manifest.js — 游戏元数据注册表（§8.1）
   自 games.js + games-extra.js 抽取的全量元数据（111 条），
   仅含 id/name/desc/icon/cat/controls，不含逻辑，首屏加载。
   本文件由 games/_extract-manifest.cjs 生成，请勿手改。
   ============================================================ */

export const MANIFEST = [
  {"id":"snake","name":"贪吃蛇","desc":"经典永不褪色，吃到果实变大但别撞墙","icon":"🐍","cat":"arcade","controls":"方向键/WASD 移动 · 空格暂停 · R 重开"},
  {"id":"tetris","name":"俄罗斯方块","desc":"消方块的永恒经典，叠高高看你能撑多久","icon":"🧱","cat":"puzzle","controls":"←→ 移动 · ↑/X 旋转 · ↓ 加速 · 空格硬降 · P 暂停"},
  {"id":"flappy","name":"像素鸟","desc":"小鸟穿管道，点一下飞一下","icon":"🐦","cat":"action","controls":"空格/点击/触屏 跳跃 · 撞到管道就重来"},
  {"id":"minesweeper","name":"扫雷","desc":"Windows 经典，找出所有地雷","icon":"💣","cat":"puzzle","controls":"左键翻开 · 右键标记 · R 重开"},
  {"id":"g2048","name":"2048","desc":"合并数字挑战极限，2014 年火爆全球","icon":"🔢","cat":"puzzle","controls":"方向键移动方块 · 同数合并 · 达到 2048 获胜"},
  {"id":"whackamole","name":"打地鼠","desc":"9 个洞口，地鼠乱窜，锤它！","icon":"🔨","cat":"arcade","controls":"点击/点击地鼠 · 限时 60 秒"},
  {"id":"memory","name":"记忆翻牌","desc":"翻开两张相同图案的卡牌，考验记忆","icon":"🃏","cat":"casual","controls":"点击/触屏翻开卡牌 · 限时挑战最少步数"},
  {"id":"pong","name":"反弹球","desc":"经典街机，两边挡板对打","icon":"🏓","cat":"arcade","controls":"W/S 移动左挡板 · ↑/↓ 移动右挡板 · 1P/2P 同屏对战"},
  {"id":"tictactoe","name":"井字棋","desc":"三连成一线，电脑不算太强","icon":"⭕","cat":"strategy","controls":"点击格子落子 · 你 X，电脑 O"},
  {"id":"gomoku","name":"五子棋","desc":"五子连珠，先连成五的一方胜","icon":"⚫","cat":"strategy","controls":"点击落子 · 黑白对弈 · 五子连一线胜"},
  {"id":"fifteen","name":"数字华容道","desc":"滑动数字 1-15 还原顺序","icon":"🔢","cat":"puzzle","controls":"点击/方向键移动数字方块"},
  {"id":"guess","name":"猜数字","desc":"4 位数字，A 表示位置对，B 表示数字对","icon":"🔐","cat":"casual","controls":"输入 4 位不重复数字 · 提交看反馈"},
  {"id":"reaction","name":"反应力","desc":"看颜色变化瞬间点击，测你的反应速度","icon":"⚡","cat":"casual","controls":"等屏幕变绿立刻点击 · 太早点击失败"},
  {"id":"hangman","name":"猜单词","desc":"经典 Hangman，猜单词拯救小人","icon":"🪢","cat":"puzzle","controls":"点击字母猜 · 6 次机会"},
  {"id":"space","name":"太空侵略者","desc":"左右移动射击外星人，1978 年街机经典","icon":"👾","cat":"arcade","controls":"← → 移动 · 空格射击 · P 暂停"},
  {"id":"breakout","name":"打砖块","desc":"弹球打砖块，1976 年雅达利经典","icon":"🧱","cat":"arcade","controls":"← → 移动挡板 · 空格发射球 · 不让球落地"},
  {"id":"shooter","name":"飞机大战","desc":"竖版射击，躲避弹幕击落敌机","icon":"✈️","cat":"arcade","controls":"← → ↑ ↓ 移动 · 空格射击 · 收集道具"},
  {"id":"maze","name":"迷宫","desc":"随机生成的迷宫，从起点走到终点","icon":"🌀","cat":"puzzle","controls":"方向键/WASD 移动 · R 重新生成"},
  {"id":"reversi","name":"黑白棋","desc":"围吃对方棋子，棋盘占多者胜","icon":"◐","cat":"strategy","controls":"点击落子 · 围住对手棋子即可翻转"},
  {"id":"sudoku","name":"数独","desc":"经典 9×9 逻辑填数，独一无二","icon":"🔲","cat":"puzzle","controls":"点击格子 + 数字键填数 · 空格清空"},
  {"id":"dino","name":"恐龙跳","desc":"像素小恐龙跳过仙人掌","icon":"🦖","cat":"arcade","controls":"空格/上箭头 跳跃 · 下蹲躲避飞行物"},
  {"id":"fruitninja","name":"切水果","desc":"挥剑切开飞起的水果，别切到炸弹","icon":"🍉","cat":"arcade","controls":"鼠标/触屏挥动切水果 · 别切炸弹"},
  {"id":"asteroids","name":"小行星","desc":"驾驶飞船射击小行星，惯性漂移","icon":"☄️","cat":"arcade","controls":"←→ 旋转 · ↑ 推进 · 空格射击"},
  {"id":"frogger","name":"青蛙过河","desc":"帮助青蛙穿过车流和河流","icon":"🐸","cat":"arcade","controls":"方向键移动 · 避免被车撞和掉水里"},
  {"id":"centipede","name":"蜈蚣","desc":"射击分段蜈蚣，避免它的头","icon":"🐛","cat":"arcade","controls":"方向键/WASD 移动 · 空格射击"},
  {"id":"pac","name":"吃豆人","desc":"吃光所有豆子，躲避幽灵","icon":"🟡","cat":"arcade","controls":"方向键移动 · 吃大力丸反追幽灵"},
  {"id":"bomber","name":"炸弹人","desc":"放炸弹炸掉砖块，躲开火焰","icon":"💣","cat":"arcade","controls":"方向键移动 · 空格放炸弹"},
  {"id":"ski","name":"滑雪","desc":"左右躲避障碍物滑下雪山","icon":"⛷️","cat":"arcade","controls":"← → 转向 · 越久越快"},
  {"id":"runner","name":"跑步者","desc":"三车道跑步，躲避车辆","icon":"🏃","cat":"arcade","controls":"← → 切换车道 · ↑ 跳跃"},
  {"id":"colorswitch","name":"颜色切换","desc":"小球穿过匹配颜色的扇形","icon":"🎨","cat":"arcade","controls":"点击/空格 跳跃 · 颜色匹配才安全"},
  {"id":"duckshoot","name":"鸭子射击","desc":"经典红白机鸭子射击","icon":"🦆","cat":"arcade","controls":"鼠标点击飞行鸭子 · 不能掉地"},
  {"id":"ringtoss","name":"套圈","desc":"把圆圈套到柱子上得分","icon":"🎯","cat":"arcade","controls":"点击/空格 抛出圆圈 · 时机要准"},
  {"id":"stacker","name":"叠叠乐","desc":"移动方块对齐堆叠，对齐越多分越高","icon":"📚","cat":"arcade","controls":"空格/点击 停止移动的方块"},
  {"id":"brick","name":"砖块射手","desc":"底部炮台射击顶部砖块","icon":"🧱","cat":"arcade","controls":"← → 移动 · 空格射击 · 鼠标瞄准"},
  {"id":"spiral","name":"螺旋","desc":"点击时机反弹出螺旋","icon":"🌀","cat":"arcade","controls":"点击/空格 跳跃 · 别撞自己"},
  {"id":"balldrop","name":"弹珠下落","desc":"点击发射弹珠到下方目标","icon":"🔮","cat":"arcade","controls":"点击/空格 发射弹珠 · 落点决定得分"},
  {"id":"planedodge","name":"飞机躲避","desc":"驾驶纸飞机躲避障碍","icon":"✈️","cat":"arcade","controls":"↑ ↓ 上升下降 · 越久越快"},
  {"id":"mazeball","name":"旋转迷宫","desc":"倾斜迷宫让小球到达目标","icon":"🧭","cat":"arcade","controls":"方向键倾斜 · 球到金色方块"},
  {"id":"skijump","name":"跳台滑雪","desc":"把握角度与速度飞最远","icon":"🎿","cat":"arcade","controls":"按住蓄力 · 松开跳跃 · 飞行中 ←→ 调整"},
  {"id":"catapult","name":"投石机","desc":"调整角度和力度投石","icon":"🪨","cat":"arcade","controls":"← → 调角度 · 空格发射"},
  {"id":"bean","name":"吃豆子","desc":"经典吃豆子变体，靠吃光升级","icon":"🫘","cat":"arcade","controls":"方向键移动 · 不能撞墙和自己"},
  {"id":"avalanche","name":"雪崩","desc":"躲避上方的雪球","icon":"❄️","cat":"arcade","controls":"← → 移动 · 雪球越大越慢"},
  {"id":"sword","name":"剑客对决","desc":"快速反应格挡，斩击对手","icon":"⚔️","cat":"action","controls":"↑↓←→ 防御方向 · 空格反击 · 时机要准"},
  {"id":"ninja","name":"忍者","desc":"跳跃挥刀斩杀飞来的飞镖","icon":"🥷","cat":"action","controls":"↑/空格 跳跃 · ↓ 挥刀 · 砍飞镖"},
  {"id":"platformer","name":"平台跳跃","desc":"经典横版平台动作","icon":"🏃","cat":"action","controls":"← → 移动 · ↑ 跳跃 · 收集金币"},
  {"id":"bullethell","name":"弹幕地狱","desc":"在弹幕中求生","icon":"✨","cat":"action","controls":"鼠标移动 · 触屏拖动 · 躲避弹幕"},
  {"id":"kungfu","name":"功夫","desc":"拳头对敌人，飞踢解决","icon":"🥋","cat":"action","controls":"← → 移动 · J 拳 · K 踢"},
  {"id":"dash","name":"滑铲","desc":"点击时机滑铲穿过障碍","icon":"🌀","cat":"action","controls":"点击/空格 滑铲 · 时机要准"},
  {"id":"hunter","name":"猎人","desc":"射击猎物得分","icon":"🏹","cat":"action","controls":"点击猎物 · 限时 60 秒"},
  {"id":"knight","name":"骑士","desc":"挥剑斩龙，躲避火焰","icon":"🛡️","cat":"action","controls":"← → 移动 · 空格挥剑"},
  {"id":"jetpack","name":"喷气背包","desc":"按住向上飞，控制高度","icon":"🚀","cat":"action","controls":"空格/点击 推进 · 撞到刺就完"},
  {"id":"robo","name":"机器人爆炸","desc":"控制机器人射击敌人","icon":"🤖","cat":"action","controls":"方向键移动 · 空格射击"},
  {"id":"swordslash","name":"剑斩","desc":"点击屏幕上飞来的物体斩断","icon":"🗡️","cat":"action","controls":"点击/触屏斩切"},
  {"id":"gunslinger","name":"枪手","desc":"西部决斗先拔枪者胜","icon":"🤠","cat":"action","controls":"等 BANG! 显示后立刻按空格"},
  {"id":"glider","name":"滑翔机","desc":"滑翔下降，穿越狭道","icon":"🪂","cat":"action","controls":"← → 微调方向 · 持续下降"},
  {"id":"bombthrow","name":"投炸弹","desc":"向远处坦克投炸弹","icon":"💣","cat":"action","controls":"← → 调整角度 · ↑ ↓ 调整力度 · 空格投"},
  {"id":"fruitpunch","name":"水果拳","desc":"按时点击出现的圆形","icon":"🥊","cat":"action","controls":"点击出现的圆圈 · 越中心分越高"},
  {"id":"runnerplat","name":"跑酷","desc":"无尽跑步，跳过陷阱","icon":"🏃","cat":"action","controls":"空格/点击 跳跃 · 双击二段跳"},
  {"id":"laser","name":"激光网格","desc":"穿越激光网格到达终点","icon":"🔴","cat":"action","controls":"方向键移动 · 别碰激光"},
  {"id":"flash","name":"闪电斩","desc":"按节奏点击斩击","icon":"⚡","cat":"action","controls":"按节奏点击 · 连击得分"},
  {"id":"castle","name":"攻城","desc":"指挥弓箭手射击城堡","icon":"🏰","cat":"action","controls":"点击城堡弱点 · 限时 90 秒"},
  {"id":"thunder","name":"雷电","desc":"驾驶战机穿越弹幕","icon":"⚡","cat":"action","controls":"方向键移动 · 空格射击"},
  {"id":"kakuro","name":"数和","desc":"填数字使横纵之和等于提示","icon":"🧮","cat":"puzzle","controls":"点击格子 · 输入 1-9 · 不能重复"},
  {"id":"bridges","name":"造桥","desc":"用桥连接所有岛屿","icon":"🌉","cat":"puzzle","controls":"点击两个相邻岛屿之间建桥"},
  {"id":"shikaku","name":"方块分割","desc":"把矩形分成若干数字标记的方块","icon":"🔲","cat":"puzzle","controls":"拖动鼠标绘制矩形"},
  {"id":"sokoban","name":"推箱子","desc":"把箱子推到目标位置","icon":"📦","cat":"puzzle","controls":"方向键移动并推动箱子"},
  {"id":"pipes","name":"管道连接","desc":"旋转管道让水流通","icon":"🚰","cat":"puzzle","controls":"点击管道旋转 · 连接到水源"},
  {"id":"sliding","name":"滑块拼图","desc":"滑动方块还原图片","icon":"🧩","cat":"puzzle","controls":"点击空白旁边的方块滑动"},
  {"id":"wordsearch","name":"单词搜索","desc":"在字母矩阵中找到所有单词","icon":"🔤","cat":"puzzle","controls":"拖动选择字母 · 找到目标单词"},
  {"id":"match3","name":"三消","desc":"交换相邻宝石，三连消除","icon":"💎","cat":"puzzle","controls":"点击两个相邻宝石交换"},
  {"id":"checkers","name":"西洋跳棋","desc":"经典跳棋，吃光对方","icon":"🟫","cat":"puzzle","controls":"点击选子 · 点击目标位置移动"},
  {"id":"shapematch","name":"形状匹配","desc":"选择正确形状填到阴影中","icon":"🔷","cat":"puzzle","controls":"点击形状拖到对应阴影"},
  {"id":"mini4","name":"迷你数独","desc":"4x4 数独入门版","icon":"🔢","cat":"puzzle","controls":"点击格子 · 输入 1-4"},
  {"id":"mathrush","name":"数学快答","desc":"快速解答数学题","icon":"➕","cat":"puzzle","controls":"点击正确答案"},
  {"id":"killer","name":"杀手数独","desc":"数独变体，笼内之和提示","icon":"🔪","cat":"puzzle","controls":"点击格子 · 输入 1-9"},
  {"id":"fill","name":"颜色填充","desc":"把同色区域扩展到整个棋盘","icon":"🎨","cat":"puzzle","controls":"点击颜色扩展区域"},
  {"id":"ice","name":"冰面滑动","desc":"冰面滑行到目标","icon":"🧊","cat":"puzzle","controls":"方向键滑行 · 撞墙停"},
  {"id":"frogjump","name":"青蛙跳","desc":"经典青蛙过河","icon":"🐸","cat":"puzzle","controls":"点击青蛙选择 · 再点目标"},
  {"id":"slide3","name":"滑块 3x3","desc":"还原数字顺序","icon":"🔢","cat":"puzzle","controls":"点击空白旁边的方块"},
  {"id":"path","name":"路径规划","desc":"一笔画连所有点","icon":"✏️","cat":"puzzle","controls":"拖动连接所有点"},
  {"id":"make24","name":"算 24","desc":"用四则运算凑 24","icon":"🎲","cat":"puzzle","controls":"点击数字和运算符"},
  {"id":"jigsaw","name":"拼图","desc":"拖动拼图块还原图","icon":"🧩","cat":"puzzle","controls":"点击两个相邻块交换"},
  {"id":"letters","name":"拼字游戏","desc":"用字母拼出目标单词","icon":"🔤","cat":"puzzle","controls":"点击字母拼写"},
  {"id":"colorcode","name":"颜色密码","desc":"猜出隐藏的颜色密码","icon":"🎨","cat":"puzzle","controls":"点击底部选色 · 提交看反馈"},
  {"id":"connect4","name":"四子棋","desc":"经典四子连珠","icon":"🟡","cat":"strategy","controls":"点击列放入棋子 · 四连成线"},
  {"id":"dotsboxes","name":"点格游戏","desc":"画线围出小方块","icon":"⬛","cat":"strategy","controls":"点击两点之间画线"},
  {"id":"go","name":"围棋","desc":"9x9 围棋入门","icon":"⚫","cat":"strategy","controls":"点击落子 · 围住对方领地"},
  {"id":"battleship","name":"战舰","desc":"寻找并击沉敌方战舰","icon":"🚢","cat":"strategy","controls":"点击格射击 · 击沉所有船"},
  {"id":"dice","name":"骰子双雄","desc":"比大小赢回合","icon":"🎲","cat":"strategy","controls":"点击掷骰"},
  {"id":"hex","name":"六角棋","desc":"六角棋盘上连边","icon":"⬡","cat":"strategy","controls":"点击六角格落子"},
  {"id":"mancala","name":"曼卡拉","desc":"播撒种子到对方基地","icon":"🌰","cat":"strategy","controls":"点击己方坑播撒"},
  {"id":"nim","name":"博弈游戏","desc":"取走最后一颗石子者输","icon":"🪨","cat":"strategy","controls":"点击堆取石子 · 1-3 颗"},
  {"id":"memory2","name":"记忆配对","desc":"翻开两张相同卡","icon":"🎴","cat":"strategy","controls":"点击翻牌 · 限时 60 秒"},
  {"id":"dots","name":"点连线","desc":"用一笔画连接所有点","icon":"🟢","cat":"strategy","controls":"点击点开始 · 拖动连接"},
  {"id":"golf","name":"高尔夫","desc":"把球推进洞","icon":"⛳","cat":"strategy","controls":"点击拖动设置力度方向"},
  {"id":"simon","name":"西蒙说","desc":"记忆颜色顺序并重复","icon":"🎵","cat":"casual","controls":"按顺序点击闪过的颜色"},
  {"id":"clicker","name":"点击狂","desc":"60 秒能点多少下","icon":"🖱️","cat":"casual","controls":"快速点击按钮"},
  {"id":"slot","name":"老虎机","desc":"转出相同符号赢分","icon":"🎰","cat":"casual","controls":"点击/空格拉杆"},
  {"id":"rps","name":"猜拳","desc":"石头剪刀布三局两胜","icon":"✂️","cat":"casual","controls":"点击石头/剪刀/布"},
  {"id":"coinflip","name":"硬币抛","desc":"猜正反 · 连胜加分","icon":"🪙","cat":"casual","controls":"点击正面/反面"},
  {"id":"blackjack","name":"21 点","desc":"比大小不超过 21","icon":"🃏","cat":"casual","controls":"点击要牌/停牌"},
  {"id":"dart","name":"飞镖","desc":"投掷飞镖命中靶心","icon":"🎯","cat":"casual","controls":"点击/触屏投掷 · 越中心分越高"},
  {"id":"archery","name":"射箭","desc":"点击时机蓄力射箭","icon":"🏹","cat":"casual","controls":"点击蓄力 · 松开射箭"},
  {"id":"bowling","name":"保龄球","desc":"点击时机投球","icon":"🎳","cat":"casual","controls":"点击/空格 投球 · 时机要准"},
  {"id":"fishing","name":"钓鱼","desc":"等鱼咬钩后及时提竿","icon":"🎣","cat":"casual","controls":"点击/空格提竿"},
  {"id":"mousetest","name":"鼠标测试","desc":"尽可能快地点击圆点","icon":"🐭","cat":"casual","controls":"点击出现的圆点"},
  {"id":"colormemory","name":"颜色记忆","desc":"记住方块序列","icon":"🌈","cat":"casual","controls":"按顺序点击方块"},
  {"id":"timing","name":"时机点击","desc":"指针转一圈 · 时机越准分越高","icon":"⏱️","cat":"casual","controls":"点击停在绿区"},
  {"id":"jumperp","name":"跳跳人","desc":"点击跳到对岸","icon":"🦘","cat":"casual","controls":"点击跳一格"},
  {"id":"speedmath","name":"速算","desc":"60 秒内做多少题","icon":"🧠","cat":"casual","controls":"输入数字 · 回车提交"},
  {"id":"numbermem","name":"数字记忆","desc":"记住显示的数字并复述","icon":"🔢","cat":"casual","controls":"输入看到的数字"},
];

export function findById(id) {
  return MANIFEST.find((m) => m.id === id) || null;
}
